services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000     
      - DATABASE_URL="postgresql://postgres:test123@localhost:5432/postgres"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=mydb
    ports :
      - "5432:5432"
    